// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMccq_tOzcMdBoIXj07fxc1ewBmoonGfI',
    appId: '1:1013798242660:android:3fdb4240a7377374791271',
    messagingSenderId: '1013798242660',
    projectId: 'idk32-61528',
    databaseURL: 'https://idk32-61528-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'idk32-61528.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPa5TlKft-uwWnhlwjyf7fHe_At-NSHJQ',
    appId: '1:1013798242660:ios:1c731ffef72db8a5791271',
    messagingSenderId: '1013798242660',
    projectId: 'idk32-61528',
    databaseURL: 'https://idk32-61528-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'idk32-61528.appspot.com',
    iosClientId: '1013798242660-pq4h3eiu75afopoe3l9nvlh0fimlhnse.apps.googleusercontent.com',
    iosBundleId: 'com.example.idc',
  );
}
